import './globals.css'
import Link from 'next/link'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<nav className="m-3 flex items-center gap-3">
					<Link href="/">Home </Link>
					<Link href="/nestedlayout">Nested layout</Link>
				</nav>

				<main>{children}</main>
			</body>
		</html>
	)
}
